### POST request to create a patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "SR",
  "email": "sr@gmail.com",
  "address": "123 Main Street",
  "dateOfBirth": "2003-01-25",
  "registeredDate": "2025-06-09"
}